name: FreeRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading NGROK.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Yumeeeekoo/FreaksRDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Yumeeeekoo/FreaksRDP/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/Yumeeeekoo/FreaksRDP/main/wallpaper.bat -OutFile wallpaper.bat
    - name: Extracting NGROK File.
      run: Expand-Archive ngrok.zip
    - name: Connect To your NGROK Account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activated Access RDP
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Membuat Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connect To Your RDP
      run: cmd /c start.bat
    - name: Your Rdp Was Created, You Can Login Now!
      run: | 
        Invoke-WebRequest https://github.com/Yumeeeekoo/FreaksRDP/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
